# Generated by Django 3.1.6 on 2021-02-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='iconne',
            new_name='icone',
        ),
    ]
