# Generated by Django 3.1.6 on 2021-02-07 16:49

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210206_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='equipe', verbose_name='Imagem'),
        ),
    ]
